enum LoginActionTypes {
  FETCH_LOGIN = 'FETCH_LOGIN',
  FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS',
  FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR',
  FETCH_LOGOUT = 'FETCH_LOGOUT'
}

export default LoginActionTypes;