enum AuthActionTypes {
  FETCH_AUTH = 'FETCH_AUTH',
  FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS',
  FETCH_AUTH_UNSUCCESS = 'FETCH_AUTH_UNSUCCESS',
  FETCH_AUTH_ERROR = 'FETCH_AUTH_ERROR'
}

export default AuthActionTypes;